version: "3.7"

networks:
  academic-network:
    driver: bridge

services:
  academic-postgres:
    image: postgres
    container_name: academic-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB_NANE}
    volumes:
      - pgdata:/data/postgres
    networks:
      - academic-network

  academic-redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - academic-network

volumes:
  pgdata:
    driver: local
